# database
type User {
  netlifyID: ID!
  stripeID: ID!
  email: String
  roles: String
  fullname: String
}

type Query {
  getUserByNetlifyID(netlifyID: ID!): User!
  getUserByStripeID(stripeID: ID!): User!
}
